services:
  - type: web
    name: saree-store-admin
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 3000
    envVars:
      - key: VITE_API_URL
        sync: false
    rootDir: admin
